# Generated by Django 4.0 on 2021-12-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=5000)),
                ('author', models.CharField(blank=True, max_length=5000)),
                ('title', models.CharField(blank=True, max_length=5000)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('url', models.CharField(blank=True, max_length=5000)),
                ('image', models.CharField(blank=True, max_length=5000)),
                ('published', models.CharField(blank=True, max_length=5000)),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('totalResults', models.CharField(blank=True, max_length=5000)),
                ('preference', models.CharField(blank=True, max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
